source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'8.0'

target 'BaseFramework' do

pod 'MJRefresh'
pod 'Masonry'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'LCTabBarController'
pod 'JSONModel'
pod 'RSKImageCropper'
end
